# https://www.home-assistant.io/integrations/group/
# https://www.home-assistant.io/docs/configuration/devices/#grouping-devices

#group:

# ------------------------------------------------------------------------

# see also scenes.yaml
ikea_light:
  name: IKEA Reading Light (3 E12s)
  entities:
    - light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_c21e1bfe_level_on_off
    - light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_168721fe_level_on_off
    - light.ikea_of_sweden_tradfri_bulb_e12_cws_opal_600lm_5c8463fe_level_light_color_on_off
 

# ------------------------------------------------------------------------

xmas_lights:
  name: X-mas lights
    - light.centralite_systems_4200_c_499d96fe_on_off                                       
    - light.centralite_systems_4200_c_21a196fe_on_off                                       

inside_lights:
  name: Inside lights
    - light.centralite_systems_4200_c_499d96fe_on_off
    - light.centralite_systems_4200_c_21a196fe_on_off
    - light.cree_connected_a_19_60w_equivalent_70e108fe_level_on_off
    - light.cree_connected_a_19_60w_equivalent_2ea506fe_level_on_off
    - light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_c21e1bfe_level_on_off
    - light.ikea_of_sweden_tradfri_bulb_e12_cws_opal_600lm_5c8463fe_level_light_color_on_off
    - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_15362ffe_level_light_color_on_off
    - light.ikea_of_sweden_tradfri_bulb_gu10_ww_400lm_eae3aafe_level_on_off
    - light.osram_lightify_a19_on_off_dim_10_year_d7100c00_level_on_off
    
# If anyone is home then this group is ON
anyone:
  name: Either of us
  entities:
    - device_tracker.julie_phone
    - device_tracker.brian_moto_e4

# If everyone is home then this group is ON
everyone:
  name: Both of us
  entities:
    - device_tracker.julie_phone                                                            
    - device_tracker.brian_moto_e4                                                          
  all: true

