#scene:

- name: red
  entities:
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_c21e1bfe_level_on_off:
      state: "off"
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_168721fe_level_on_off:
      state: "off"
    light.ikea_of_sweden_tradfri_bulb_e12_cws_opal_600lm_5c8463fe_level_light_color_on_off:
      state: "on"
      brightness: 255
      color:
        - red: 255
        - blue: 0
        - green: 0
      
- name: blue
  entities:
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_c21e1bfe_level_on_off:
      state: "off"
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_168721fe_level_on_off:
      state: "off"
    light.ikea_of_sweden_tradfri_bulb_e12_cws_opal_600lm_5c8463fe_level_light_color_on_off:
      state: "on"
      brightness: 255
      color:
        - red: 0
        - blue: 255
        - green: 0
      
- name: green
  entities:
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_c21e1bfe_level_on_off:
      state: "off"
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_168721fe_level_on_off:
      state: "off"
    light.ikea_of_sweden_tradfri_bulb_e12_cws_opal_600lm_5c8463fe_level_light_color_on_off:
      state: "on"
      brightness: 255
      color:
        - red: 0
        - blue: 0
        - green: 255

- name: white
  entities:
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_c21e1bfe_level_on_off:
      state: "on"
      brightness: 255
    light.ikea_of_sweden_tradfri_bulb_e12_w_op_ch_400lm_168721fe_level_on_off:
      state: "on"
      brightness: 255
    light.ikea_of_sweden_tradfri_bulb_e12_cws_opal_600lm_5c8463fe_level_light_color_on_off:
      state: "on"
      brightness: 255
      color:
        - red: 255
        - blue: 255
        - green: 255
      
