
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/

econet: toxicwater123

spotify: 3d04f618e1ec40d1a8bdf4e106fb936

telegram: 2018647788:AAECRF69MzCwMfFVy7PPeUwa2feHDFcnU7U


