#device_tracker:

# Set up for using Traccar to keep tabs on cellphone locations
#
#- platform: traccar
#  host: traccar
#  port: 8082
#  username: HA
#  password: haTravel
#  event: [ 'device_moving', 'device_stopped', 'geofence_enter', 'geofence_exit', 'device_online', 'text_message' ]

# Integration with OpenWrt
- platform: ubus
  host: 192.168.1.3
  username: hass
  password: OatsAndGroats
  dhcp_software: none
